#!/bin/bash
# borg-cron.sh - rewrite the plugin's cron entry from the saved settings.
# Run after any settings change and on array start.

PLUGIN=borgbackup
BOOT=/boot/config/plugins/$PLUGIN
CRON_FILE=/etc/cron.d/$PLUGIN
RUN="/usr/local/emhttp/plugins/$PLUGIN/scripts/borg-backup.sh"

# NB: $CRON below is a *setting* (the custom expression), not this file's path -
# keep those names distinct, the config is sourced straight into this shell.
[[ -r $BOOT/$PLUGIN.cfg ]] && . "$BOOT/$PLUGIN.cfg"

disable() { rm -f "$CRON_FILE"; /usr/local/sbin/update_cron 2>/dev/null; exit "${1:-0}"; }

case "${SCHEDULE:-daily}" in
  hourly)   SPEC="${MINUTE:-0} * * * *" ;;
  daily)    SPEC="${MINUTE:-0} ${HOUR:-3} * * *" ;;
  weekly)   SPEC="${MINUTE:-0} ${HOUR:-3} * * ${WEEKDAY:-0}" ;;
  monthly)  SPEC="${MINUTE:-0} ${HOUR:-3} ${MONTHDAY:-1} * *" ;;
  custom)
    # Exactly five fields of cron-safe characters: nothing may run on past the
    # schedule into the command half of the crontab line.
    if [[ ! ${CRON:-} =~ ^[0-9*,/-]+([[:space:]]+[0-9*,/-]+){4}$ ]]; then
      logger -t "$PLUGIN" "invalid custom cron expression - schedule not installed"
      disable 1
    fi
    SPEC="$CRON"
    ;;
  *)        disable 0 ;;   # covers "disabled" and anything unrecognised
esac

cat >"$CRON_FILE" <<EOF
# Generated by the $PLUGIN plugin - edit the schedule in the web UI instead.
$SPEC root $RUN &>/dev/null
EOF

/usr/local/sbin/update_cron 2>/dev/null
exit 0
